import Head from 'next/head'
import { useContext } from "react";
import { GlobalContext } from "@utils/GlobalContext";
import Link from 'next/link';
import { createClient } from '@supabase/supabase-js';

export async function getServerSideProps(context) {
  const id = context.params.id
  const supabaseAdmin = createClient(process.env.SUPABASE_URL || '', process.env.SUPABASE_ANON_KEY || '');

  // const { data } = await supabaseAdmin.from('song').select(`*, artist (*)`).match({ id: id });
  const { data } = await supabaseAdmin
    .from('song')
    .select(`
      id,
      name,
      youtubeId,
      albumCoverUrl,
      artistId,
      artist (
        id,
        name,
        genre,
        coverUrl
      )
    `)
    .match({ id: id });

  return {
    props: {
      song: data[0]
    }
  };
}

export default function Home({ song }) {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <div>
      <Head>
        <title>{song.name} - {song.artist.name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="dark:bg-neutral-900 min-h-screen p-8 md:p-12">
        <div className="max-w-lg mx-auto">
          
          <nav className="flex justify-between mb-8 gap-x-4">
            <Link href="/">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Songs</span>
            </Link>
            <Link href="/artists">
              <span className="text-blue-500 hover:text-blue-600 font-medium transition-all hover:cursor-pointer">Artists</span>
            </Link>
            <div onClick={() => setDarkMode(!darkMode)} className="transition-all cursor-pointer w-12 h-7 dark:bg-blue-500 bg-neutral-200 rounded-full relative">
              <div className="h-5 w-5 bg-white rounded-full absolute top-1 transition-all dark:left-6 left-1"></div>
            </div>
          </nav>

          <div>
            <h1 className="text-neutral-700 dark:text-gray-100 text-xl font-bold">{song.name}</h1>
            <Link href={`/artist/${song.artist.id}`}>
              <a className="block mt-1 font-medium text-sm sm:text-base text-neutral-700 dark:text-gray-300 hover:!text-blue-600 transition-all cursor-pointer">{song.artist.name}</a>
            </Link>
          </div>

          <div className="mt-4">
            <div className="h-60 sm:h-72 lg:h-80 mb-4">
              <iframe
                width="100%"
                height="100%"
                src={`https://www.youtube.com/embed/${song.youtubeId}`}
                frameBorder="0"
                allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture"
                allowFullScreen
              />
            </div>
            <Link href="/">
              <span className="text-blue-500 hover:text-blue-600 transition-all cursor-pointer text-sm font-medium">Back to Song List</span>
            </Link>
          </div>
        </div>
      </main>
    </div>
  )
}
